Repository TeamS2-ICCAS2024/ZEN-android, pull requests merged in 2024-07, with the labels that each got.

#2 [feat] 테트리스 게임 기능 고도화 #1
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/components/BasicBackground.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/AppIcon.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/GameBody.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameOverScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/tetrisComponents/GameButton.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/tetrisComponents/LedNumber.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/tetrisComponents/PlayControlButton.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/tetris_bpm.xml
  app/src/main/res/drawable/tetris_game_heart_filled.png
  app/src/main/res/drawable/tetris_game_heart_unfilled.png
  app/src/main/res/drawable/tetris_game_over.png
  app/src/main/res/drawable/zen_brown_logo.png
  app/src/main/res/drawable/zen_white_logo.png
Labels: enhancement, feat, 지원, refactor

#4 [feat] 감정일기 제공을 위한 gpt연동 챗봇 서비스를 구현 #3
  .idea/deploymentTargetSelector.xml
  Outline/Arrows/Arrow Left.png
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/iccas/zen/BuildConfig.java
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/Message.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/SelectEmotionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/components/EmotionButton.kt
  app/src/main/java/com/iccas/zen/presentation/home/GameSelectScreen.kt
  app/src/main/res/drawable/angry.png
  app/src/main/res/drawable/arrow_up.png
  app/src/main/res/drawable/bao.png
  app/src/main/res/drawable/happy.png
  app/src/main/res/drawable/sad.png
  app/src/main/res/drawable/soso.png
  gradle/libs.versions.toml
Labels: feat, 보람

#7 [fix] 테트리스 게임 버튼 로직 오류 수정 #6
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/GameBody.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameOverScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
  app/src/main/res/drawable/tetris_game_volume_off.png
  app/src/main/res/drawable/tetris_game_volume_on.png
Labels: bug, fix, 지원

#11 [feat] 테트리스 방해요소 기능 추가 구현
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/Spirit.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/warning.png
Labels: feat, 준혁

#15 [refactor] 요가 게임 고도화 #14
  app/src/main/assets/denseModel.tflite
  app/src/main/assets/dense_model.tflite
  app/src/main/java/com/iccas/zen/presentation/yoga/MoveNetModel.kt
  app/src/main/java/com/iccas/zen/presentation/yoga/YogaGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/yoga/YogaPose.kt
  app/src/main/java/com/iccas/zen/presentation/yoga/YogaResultContent.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/corpose.jpg
  app/src/main/res/drawable/easy_pose.png
  app/src/main/res/drawable/leaf.png
  app/src/main/res/drawable/standing_forward_bend.png
  app/src/main/res/drawable/yoga_bridge_pose.png
  app/src/main/res/drawable/yoga_cat_cow_pose.png
  app/src/main/res/drawable/yoga_child_pose.png
  app/src/main/res/drawable/yoga_cobra_pose.jpg
  app/src/main/res/drawable/yoga_leaf_filled.png
  app/src/main/res/drawable/yoga_leaf_unfilled.png
  app/src/main/res/drawable/yoga_tree_pose.png
Labels: fix, 지원, refactor

#21 [Feat] 테트리스 로직 수정, 온보딩,회원가입 UI 구현
  app/src/main/java/com/iccas/zen/MainActivity.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/onBoarding/onBoardingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/signup/SignupScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/Spirit.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/measure_heart_rate.png
  app/src/main/res/drawable/mindful_yoga.png
  app/src/main/res/drawable/paper_with_tape.png
  app/src/main/res/drawable/reflect_on_your_day.png
  app/src/main/res/drawable/self_assessment.png
Labels: feat, fix, 준혁

#22 [Feat] 캐릭터 콜렉션 페이지 구현 및 네비게이션 로직 개
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharacterPopup.kt
  app/src/main/java/com/iccas/zen/presentation/character/CollectionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/character/charSelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/NavigationBar.kt
  app/src/main/java/com/iccas/zen/presentation/home/GameSelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/signup/SignupScreen.kt
  app/src/main/res/drawable/question_mark.png
Labels: feat, fix, 현욱

#24 [feat] 챗봇 서비스 고도화 구현
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/SelectEmotionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/components/EmotionButton.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/components/EmotionHeader.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/components/TopBar.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/angry.png
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/chat_angry.png
  app/src/main/res/drawable/chat_arrow_up.png
  app/src/main/res/drawable/chat_bao.png
  app/src/main/res/drawable/chat_happy.png
  app/src/main/res/drawable/chat_sad.png
  app/src/main/res/drawable/chat_soso.png
  app/src/main/res/drawable/happy.png
  app/src/main/res/drawable/sad.png
  zen-watch/src/main/res/values/styles.xml
Labels: feat, 보람

#26 feat: 레포트 기능 구현 (#23)
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/components/NavigationBar.kt
  app/src/main/java/com/iccas/zen/presentation/report/AngerGameReport.kt
  app/src/main/java/com/iccas/zen/presentation/report/AngerGameSelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportBox/EmotionDiarySelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportBox/ReportSelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/SelfDiagnosisSelect.kt
  app/src/main/res/drawable/heart_outline.png
Labels: feat, 현욱

#30 [feat] 설정 화면 추가
  .gitignore
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharScreen.kt
  app/src/main/java/com/iccas/zen/presentation/home/PersonalSettingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/home/SettingScreen.kt
Labels: feat, 현욱

#31 [fix] 테트리스 방해요소 로직 오류 해결 및 알림 UI 고도화 #12
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
  app/src/main/res/drawable/disable_rotate3.png
  app/src/main/res/drawable/random3.png
  app/src/main/res/drawable/reverse_control4.png
Labels: bug, feat, fix, 준혁, refactor

#34 [feat] 감정일기 상세 화면 ui 구현
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportDetailScreen.kt
Labels: feat, 보람

#35 feat: 캐릭터 화면 및 콜렉션 API 연결 구현 (#33)
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/iccas/zen/presentation/character/CharScreen.kt
  app/src/main/java/com/iccas/zen/presentation/character/Character.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharacterViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/character/CollectionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/UserResponse.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/res/drawable/char_bao1.png
  app/src/main/res/drawable/char_bao2.png
  app/src/main/res/drawable/char_bao3.png
  app/src/main/res/drawable/char_mozzi1.png
  app/src/main/res/drawable/char_mozzi2.png
  app/src/main/res/drawable/char_mozzi3.png
  app/src/main/res/drawable/char_sky1.png
  app/src/main/res/drawable/char_sky2.png
  app/src/main/res/drawable/char_sky3.png
  app/src/main/res/xml/network_security_config.xml
Labels: feat, 현욱

#37 [feat] 캐릭터 배경 관련 구현 및 API 연결
  app/src/main/java/com/iccas/zen/presentation/character/Backgrounds.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharScreen.kt
  app/src/main/java/com/iccas/zen/presentation/character/CollectionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/UserResponse.kt
  app/src/main/res/drawable/background1.png
  app/src/main/res/drawable/background2.png
  app/src/main/res/drawable/background3.png
  app/src/main/res/drawable/background4.png
Labels: feat, 현욱

#39 [feat] Retrofit 모듈화 #38
  app/build.gradle.kts
  app/src/main/java/com/iccas/zen/MainActivity.kt
  app/src/main/java/com/iccas/zen/data/dto/auth/request/LoginRequest.kt
  app/src/main/java/com/iccas/zen/data/dto/auth/response/LoginResponse.kt
  app/src/main/java/com/iccas/zen/data/dto/user/response/ChangeBackgroundResponse.kt
  app/src/main/java/com/iccas/zen/data/dto/user/response/UserResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/AuthApi.kt
  app/src/main/java/com/iccas/zen/data/remote/RetrofitModule.kt
  app/src/main/java/com/iccas/zen/data/remote/UserApi.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/auth/LoginScreen.kt
  app/src/main/java/com/iccas/zen/presentation/auth/SignupScreen.kt
  app/src/main/java/com/iccas/zen/presentation/auth/WelcomeScreen.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharScreen.kt
  app/src/main/java/com/iccas/zen/presentation/character/CharacterViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/character/CollectionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/UserResponse.kt
  app/src/main/java/com/iccas/zen/presentation/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/signup/SignupScreen.kt
  gradle/libs.versions.toml
Labels: feat, 지원

#41 [feat] 자가진단 레포트 UI 구현 #32
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/components/NavigationBar.kt
  app/src/main/java/com/iccas/zen/presentation/diagnosis/DiagnosisScreen.kt
  app/src/main/java/com/iccas/zen/presentation/diagnosis/ResultScreen.kt
  app/src/main/java/com/iccas/zen/presentation/diagnosis/SurveyScreen.kt
  app/src/main/java/com/iccas/zen/presentation/heartreport/Heartreport.kt
  app/src/main/java/com/iccas/zen/presentation/heartreport/Heartreport2.kt
  app/src/main/java/com/iccas/zen/presentation/report/AngerGameReport.kt
  app/src/main/java/com/iccas/zen/presentation/report/AngerGameSelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportBox/EmotionDiarySelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportBox/ReportSelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/SelfDiagnosisSelect.kt
  app/src/main/res/drawable/clapgirl.png
  app/src/main/res/drawable/collect2_icon.png
  app/src/main/res/drawable/collect_icon.png
  app/src/main/res/drawable/diagtext.png
  app/src/main/res/drawable/diary_icon.png
  app/src/main/res/drawable/game_icon.png
  app/src/main/res/drawable/go_left.png
  app/src/main/res/drawable/go_right.png
  app/src/main/res/drawable/main_icon.png
  app/src/main/res/drawable/report_icon.png
Labels: feat, fix, 준혁, refactor

#45 [feat]: 테트리스 방해요소 주기 수정
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
Labels: fix, 준혁

#50 [feat] 회원가입 api 연결 및 auth 도메인 고도화 #49
  app/src/main/java/com/iccas/zen/data/dto/auth/request/SignUpRequest.kt
  app/src/main/java/com/iccas/zen/data/remote/AuthApi.kt
  app/src/main/java/com/iccas/zen/data/remote/RetrofitModule.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/auth/LoginScreen.kt
  app/src/main/java/com/iccas/zen/presentation/auth/SignupScreen.kt
  app/src/main/java/com/iccas/zen/presentation/auth/WelcomeScreen.kt
  app/src/main/java/com/iccas/zen/presentation/auth/authComponents/AuthButton.kt
  app/src/main/java/com/iccas/zen/presentation/auth/authComponents/UserInfoInputBox.kt
Labels: feat, 지원, refactor

#53 [feat] 감정일기 화면 구현 및 자가진단 api 연결
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/DiaryCharSelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/NavigationBar.kt
  app/src/main/java/com/iccas/zen/presentation/report/SelfDiagnosisReport.kt
  app/src/main/java/com/iccas/zen/presentation/report/SelfDiagnosisSelect.kt
Labels: feat, fix, 현욱

#58 [feat] user 답변 저장 api 연동 및 화면 연동 #40
  app/src/main/java/com/iccas/zen/data/dto/auth/request/EmotionDiaryPostRequest.kt
  app/src/main/java/com/iccas/zen/data/dto/auth/response/ApiResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/DiaryApi.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/DiaryCharSelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/SelectEmotionScreen.kt
Labels: feat, 보람

#61 [Fix] : 전체적인 UI,로직 수정
  app/src/main/java/com/iccas/zen/presentation/character/CollectionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/DiaryCharSelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/SelectEmotionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/components/NavigationBar.kt
  app/src/main/java/com/iccas/zen/presentation/heart/viewmodel/MeasureHeartViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/heartreport/Heartreport.kt
  app/src/main/java/com/iccas/zen/presentation/home/PersonalSettingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/home/SettingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/onBoarding/onBoardingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameOverScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/res/drawable/collect_icon.png
  app/src/main/res/drawable/diary_icon.png
  app/src/main/res/drawable/game_icon.png
  app/src/main/res/drawable/main_icon.png
  app/src/main/res/drawable/report_icon.png
Labels: fix, refactor

#63 [fix] 테트리스 게임 결과가 중복 저장되는 오류 해결 #62
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/heart/MeasureBaseScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/TetrisGameScreen.kt
  app/src/main/java/com/iccas/zen/presentation/tetris/logic/GameViewModel.kt
Labels: bug, fix, 지원, hotfix

#67 [feat] 테트리스 게임 결과 리스트 조회 api 연결
  app/src/main/java/com/iccas/zen/data/dto/tetris/response/TetrisResultListResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/TetrisApi.kt
  app/src/main/java/com/iccas/zen/presentation/diagnosis/ResultScreen.kt
  app/src/main/java/com/iccas/zen/presentation/diagnosis/SurveyScreen.kt
  app/src/main/java/com/iccas/zen/presentation/heart/viewmodel/MeasureHeartViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/heartreport/Heartreport.kt
  app/src/main/java/com/iccas/zen/presentation/onBoarding/onBoardingScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/viewModel/ReportViewModel.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/res/drawable/onboarding_paper_with_tape.png
  app/src/main/res/drawable/survey_clap_girl.png
Labels: feat, 지원, refactor

#68 [feat] 유저에 해당하는 일기조회 api 연결
  app/src/main/java/com/iccas/zen/data/dto/emotionDiary/request/EmotionDiaryPostRequest.kt
  app/src/main/java/com/iccas/zen/data/dto/emotionDiary/response/DiaryListGetResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/DiaryApi.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/ChatViewModel.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/viewModel/ReportViewModel.kt
Labels: feat, 보람

#71 [feat] tetris result 상세조회 api 연결 #70
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/iccas/zen/data/dto/tetris/response/TetrisResultListResponse.kt
  app/src/main/java/com/iccas/zen/data/dto/tetris/response/TetrisResultResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/TetrisApi.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/components/TitleWithHighlighter.kt
  app/src/main/java/com/iccas/zen/presentation/heartreport/Heartreport2.kt
  app/src/main/java/com/iccas/zen/presentation/report/AngerGameSelect.kt
  app/src/main/java/com/iccas/zen/presentation/report/GameReportListScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/GameReportScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/reportComponents/EmotionDiarySelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/reportComponents/ReportSelectBox.kt
  app/src/main/java/com/iccas/zen/presentation/report/reportComponents/ReportTItle.kt
  app/src/main/java/com/iccas/zen/presentation/report/viewModel/ReportViewModel.kt
  app/src/main/java/com/iccas/zen/ui/theme/Color.kt
  app/src/main/java/com/iccas/zen/utils/DateTimeUtils.kt
Labels: feat, 지원, refactor

#73 [feat] 일기 상세조회 api 연결
  app/src/main/java/com/iccas/zen/data/dto/emotionDiary/response/DiaryDetailResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/DiaryApi.kt
  app/src/main/java/com/iccas/zen/navigation/NavGraph.kt
  app/src/main/java/com/iccas/zen/presentation/chatBot/SelectEmotionScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/DiaryDetailScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/ReportDetailScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/viewModel/ReportViewModel.kt
Labels: feat, 보람

#76 [feat] 감정에 따른 일기조회 api 연결
  app/src/main/java/com/iccas/zen/data/dto/emotionDiary/response/DiaryByEmotionResponse.kt
  app/src/main/java/com/iccas/zen/data/remote/DiaryApi.kt
  app/src/main/java/com/iccas/zen/presentation/report/DiaryDetailScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/EmotionDiarySelectScreen.kt
  app/src/main/java/com/iccas/zen/presentation/report/viewModel/ReportViewModel.kt
  app/src/main/res/drawable/chat_angry.png
  app/src/main/res/drawable/chat_happy.png
  app/src/main/res/drawable/chat_sad.png
  app/src/main/res/drawable/chat_soso.png
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/img_1.png
  app/src/main/res/drawable/img_2.png
Labels: feat, 보람
